package com.ddiehl.reddit.identity;
//{
//    "beta": boolean value,
//    "clickgadget": boolean value,
//    "collapse_read_messages": boolean value,
//    "compress": boolean value,
//    "creddit_autorenew": boolean value,
//    "default_comment_sort": one of (`confidence`, `old`, `top`, `qa`, `controversial`, `new`),
//    "domain_details": boolean value,
//    "email_messages": boolean value,
//    "enable_default_themes": boolean value,
//    "hide_ads": boolean value,
//    "hide_downs": boolean value,
//    "hide_from_robots": boolean value,
//    "hide_locationbar": boolean value,
//    "hide_ups": boolean value,
//    "highlight_controversial": boolean value,
//    "highlight_new_comments": boolean value,
//    "ignore_suggested_sort": boolean value,
//    "label_nsfw": boolean value,
//    "lang": a valid IETF language tag (underscore separated),
//    "mark_messages_read": boolean value,
//    "media": one of (`on`, `off`, `subreddit`),
//    "min_comment_score": an integer between -100 and 100,
//    "min_link_score": an integer between -100 and 100,
//    "monitor_mentions": boolean value,
//    "newwindow": boolean value,
//    "no_profanity": boolean value,
//    "num_comments": an integer between 1 and 500,
//    "numsites": an integer between 1 and 100,
//    "organic": boolean value,
//    "over_18": boolean value,
//    "private_feeds": boolean value,
//    "public_votes": boolean value,
//    "research": boolean value,
//    "show_flair": boolean value,
//    "show_gold_expiration": boolean value,
//    "show_link_flair": boolean value,
//    "show_promote": boolean value,
//    "show_stylesheets": boolean value,
//    "show_trending": boolean value,
//    "store_visits": boolean value,
//    "theme_selector": subreddit name,
//    "threaded_messages": boolean value,
//    "use_global_defaults": boolean value,
//}
public class Prefs {

}
